#!/bin/bash
base=`dirname $0`
data=$base/../data
mkdir -p $data

echo "Generating ssh-keys"
ssh-keygen -N "" -q -f $data/docker
echo "Getting geoip files"
rsync -az root@mtv01-accel07.hq.instart.co:/opt/geoip/Geo* $data
